### ISSUE TITLE
Support for different fonts of 'TextSegment' upon state changes

### ISSUE THREAD

**Issue by barthopster** [nedap/segnify-ios#12]
**Describe the feature**
As a developer, I want to specify a font for every state of a `TextSegment` instance, so the `TextSegment` instance shows its text with a bold font upon selection, instead of the currently used regular font.

**Rules/Acceptance criteria**
* R1: The UI should 'mimic' the UI of the old segmentation implementation.

**Comment by martias** [comment]
Hey @barthopster It would be nice to put some prio to this issue to have it ready before publishing Client Agenda. The current version has the bold in the selected segment, so not having it would feel like a regression.

**Comment by dregatos** [comment]
hey @vpetrykov, could you please investigate this one?
